#!/bin/bash
#PBS -q hpcintro
#PBS -N log
#PBS -l feature=XeonX5550
#PBS -l walltime=20:00
LOOPS=10000
OPTS=("nat" "lib" "blk")
MNK=("nmk" "nkm" "mnk" "mkn" "kmn" "knm") 
LOGEXT=dat
/bin/rm -f *.$LOGEXT
for mode in "${OPTS[@]}"
do
	n=20
	while [ $n -lt 100 ] 
	do
	m=20
		while [ $m -lt 100 ]
		do	
		k=20
			while [ $k -lt 100 ]
			do
			if [ "nat" = "$mode" ]
			then
				for order in "${MNK[@]}"
				do
					./matmult_f.gcc $mode $order $m $n $k >> "$mode"_"$order"."$LOGEXT"
				done
			else
				./matmult_f.gcc $mode $m $n $k >> $mode."$LOGEXT"
			fi
			k=$(($k+20))
			done
		m=$(($m+20))
		done
	n=$(($n+20))
	done
done
echo $count
# time to say 'Good bye' ;-)
#
exit 0

